### ISSUE TITLE
Use 3rd positional coordinate in superwow's UnitPosition

### ISSUE THREAD

**Issue by balakethelock** [i2ichardt/HealersMate#12]
https://github.com/i2ichardt/HealersMate/blob/e9d53b76e6f8364f04f6e798af68d913060df7cb/HMUtil.lua#L418
UnitXP's distance and superwow's UnitPosition should give the same result and be 100% accurate if you also include elevation that is provided by superwow's UnitPosition function `d = √ [(x2 – x1)² + (y2 – y1)² + (z2 – z1)²]`

**Comment by OldManAlpha** [comment]
Thanks for clarifying that. I was thinking that the `y` would've been elevation, so I had assumed it only returned 2 numbers when the second return variable was returning what I thought would've been the `z` coordinate.

**Comment by OldManAlpha** [comment]
Fixed in d936531f405a9c2d1c733c814a23b9a379e5cb53.
