### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by OldManAlpha** [i2ichardt/HealersMate#2]
Hey, I realize this is not quite the proper channel, but I'd like to get into contact with you about contributing to/forking HealersMate. I sent an email, but I'm not entirely sure if it is active.

**Comment by i2ichardt** [comment]
What's up? rj299@yahoo.com

**Comment by OldManAlpha** [comment]
I sent an email to your address a few days ago. Did you receive it?

**Comment by i2ichardt** [comment]
I got one from someone saying thank you. Don't know if it was you. They didn't ask me anything.

**Comment by i2ichardt** [comment]
I have a version of this addon with options added to adjust the size and colors of the frames that has a crash bug that needs found and fixed. I haven't messed with turtle wow due to being a hassle to find dungeon groups after being spoiled with dungeon finder. So I haven't worked on it more than that.

**Comment by i2ichardt** [comment]
If you wanted to take that version and go from there with it I wouldn't care.

**Comment by i2ichardt** [comment]
I'm currently playing once human. Derp

**Comment by OldManAlpha** [comment]
Oh well, I'll just paste what I said in the email:

Hey Richard, I first want to say thank you for creating HealersMate as there really is no other addon for 1.12 that does what it does without massive compromises. I've been tweaking around with your addon to add additional features, such as support for side mouse buttons and refactoring the code to make it more compact, reducing its line count by half. I also want to add support for raids, add SuperWoW support, and create a more customizable and compact UI. I'd like to publish this fork in some capacity, but I noticed your project does not have a license. Would you clarify what people are allowed to do with your code? I'm also open to publishing my changes to the main HealersMate GitHub page. If you'd write me back or contact me on Discord (username: oldmana), I'd appreciate it!

**Comment by i2ichardt** [comment]
Didn't get that unless it went to spam. I'm just a hobbist that programs for fun when I have nothing else to do. I sent you a collaborator invite.

**Comment by OldManAlpha** [comment]
Thank you, although I do want to have a larger discussion about your vision for HealersMate. I'm not sure if you'll agree with the changes I desire to make, which is also why I also mentioned forking as to not ruin your vision. I'm trying to make HealersMate kind of more like retail's VuhDo addon with some extra spice. I've changed the look of the frames a bit and intend to make them even more compact and added a spell helper tooltip. This is what I have right now:

![image](https://github.com/user-attachments/assets/76aae97a-eb5a-4c81-b3ef-cee29c3ed5d3)
