### ISSUE TITLE
Feature Request: Option to Target on Cast

### ISSUE THREAD

**Issue by Oxynium** [i2ichardt/HealersMate#5]
Hello, any chance to add an option to Target ally when casting a heal? Or perhaps an option to choose Spell Name and action like Target to work on single mouse click?

Overall, this addon could finally be a working and modern HealBot experience on TurtleWoW, thank you for your work!

**Comment by OldManAlpha** [comment]
I'm curious why you want that functionality. Is there another addon that requires you to target a player or is it just personal preference?

**Comment by Oxynium** [comment]
> I'm curious why you want that functionality. Is there another addon that requires you to target a player or is it just personal preference?

It's an option in modern HealBot, "Auto Target" is the name I think. It just allows to do multiple things with a single mouse button. Targeting, and by that showing target nameplate of whoever I am healing right now can help reacting better. 


Other features I am missing right now: 
-Timers on HoTs I casted.
-When settings/customization is introduced, Test mode is really helpful (so people can setup their bars sitting in Stormwind). An option to generate 5/10/20/40 bars to take a look if everything fits nicely.
-Ability to mark certain raid members as Tanks and creating extra group with only tanks in it.

Overall, so far it is looking great. I can't code but I can be tester if that will help.

**Comment by OldManAlpha** [comment]
I'd say most of these things are planned for 2.0.0 release, with the exception of HoT timers. Since vanilla can't see the timers on other players' buffs, that makes things a bit complicated. So that'll be a further down the road thing.

**Comment by Oxynium** [comment]
> I'd say most of these things are planned for 2.0.0 release, with the exception of HoT timers. Since vanilla can't see the timers on other players' buffs, that makes things a bit complicated. So that'll be a further down the road thing.

HoT timers for spells casted by myself are helpful enough, speaking as a druid player.

**Comment by OldManAlpha** [comment]
I mean to say, if the buff isn't on yourself, you cannot see the time on it.

**Comment by OldManAlpha** [comment]
Implemented auto targeting in 80db44766c0b3a00b52710f6535de620d0adaae9, now in the latest release. The other features suggested will be implemented later.
